### ISSUE TITLE
The GUI move hero moves all friendly heroes to the same location

### ISSUE THREAD

**Issue by Charlie-Zheng** [Charlie-Zheng/CPSC-233-Project#3]
The GUI move hero moves all friendly heroes to the same location as can be seen when 2 heroes are spawned.

**Comment by Charlie-Zheng** [comment]
While moving units on the map, please use Map.moveHero() and not by Unit.setYX()

Map.moveHero() will call Unit.setYX(), but also update the unitMap in Map to the corresponding value.

**Comment by Font-Of-Life** [comment]
Fixed it now we can move the units separately, and shows the attack range and movement range for both enemy and players units.
